server:
  port: 7001

spring:
  application:
    name: seckill_web

  redis: # redis ??
    host: 192.168.111.128
    database: 0
    lettuce:
      pool:
        enabled: true
        max-active: 100
        max-idle: 20
        min-idle: 5

rocketmq:
  name-server: 192.168.111.128:9876     # rocketMq?nameServer??
  producer:
    group: powernode-group        # ?????
    send-message-timeout: 3000  # ?????????
    retry-times-when-send-async-failed: 2  # ????????????
    max-message-size: 4194304       # ???????


