server:
  port: 8080
  servlet:
    context-path: /demo
# 下面的配置等同于 TaskConfig
#spring:
#  task:
#    scheduling:
#      pool:
#        size: 20
#      thread-name-prefix: Job-Thread-
spring:
  mail:
    username: 534096094@qq.com
    password: gtstkoszjelabijb
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
