server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rocketmq_p?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8

rocketmq:
#  name-server: 192.168.187.128:9876;192.168.187.129:9876
  name-server: 192.168.18.67:9876
  producer:
    group: spring-boot-producer-group

