server:
  port: 8888

spring:
  datasource:
    ssm:
      driver-class-name: com.mysql.jdbc.Driver
      password: 123456
      url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
      username: root

logging:
  config: classpath:log4j2.xml

