server:
  port: 7777


spring:
  # spring cache整合
  cache:
    type: redis
    redis:
      #允许缓存空值,默认true(能防止缓存穿透，也叫暴力缓存。)
      cache-null-values: true
      # 过期时间(这里是30min)。缺省情况下，表项永远不会过期。单位毫秒
      time-to-live: 1800000
      # key前缀
      key-prefix: 'cache:'
      # 当写入Redis时是否使用key前缀，默认true
      use-key-prefix: true

  # redis配置
  redis:
    # redis地址
    host: 127.0.0.1
    # 端口
    port: 6379
    # 数据库索引
    database: 0
    # 连接超时时间（毫秒）
    timeout: 30000ms
    # jedis连接池
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最小空闲连接
        min-idle: 1
        # 连接池中的最大空闲连接
        max-idle: 100

