spring:
  profiles: local
  datasource:
      url: jdbc:mysql://localhost:3306/_study_spring_boot_vue?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
logging:
  config: classpath:logback-local.xml
