server:
  port: 8080
  servlet:
    context-path: /demo
# 若要访问端点信息，需要配置用户名和密码
spring:
  security:
    user:
      name: xkcoding
      password: 123456
management:
  # 端点信息接口使用的端口，为了和主系统接口使用的端口进行分离
  server:
    port: 8090
    servlet:
      context-path: /sys
  # 端点健康情况，默认值"never"，设置为"always"可以显示硬盘使用情况和线程情况
  endpoint:
    health:
      show-details: always
  # 设置端点暴露的哪些内容，默认["health","info"]，设置"*"代表暴露所有可访问的端点
  endpoints:
    web:
      exposure:
        include: '*'
#
#  management.security.enabled=false
#
#  spring.redis.host=118.24.44.169
#
#  info.app.id=hello
#  info.app.version=1.0.0
#
#  #endpoints.metrics.enabled=false
#  endpoints.shutdown.enabled=true
#
#  #endpoints.beans.id=mybean
#  #endpoints.beans.path=/bean
#  #endpoints.beans.enabled=false
#  #
#  #endpoints.dump.path=/du
#
#
#  # \u5173\u95ED\u6240\u6709\u7AEF\u70B9\u8BBF\u95EE
#  #endpoints.enabled=false
#  #endpoints.beans.enabled=true
#
#  management.context-path=/manage
#
#  management.port=8181

