spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootvue?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 20200120
mybatis:
  mapperLocations: classpath:/mapper/*.xml
